#+TITLE: README

* declare
პროგრამა უცხოეთში ნაყიდი ამანათების სამართავად და დასადეკლარირებლად.
** features
აქ წერია მთლიანი პროგრამის ხედვა. სექციაში [[გეგმა]] ჩამოვთვლი პირველი ეტაპისთვის რის გაკეთებას შევეცდები
 - გაკეთებულ შეკვეთებზე ინფორმაციის გაერთიანება
   ebay, amazon
 - საქართველოში ჩამომტანი სერვისების ავტომატური მართვა
   - tracking code დამატება და დეკლარირება
   - ჩამოტანის ხარჯის დათვლა ინვოისებიდან
 - სხვისი ამანათების მართვა
   იმიტომ რომ სახლში მარტივად გაკეთების სწავლაც დაეზარებათ და მაინც მე უნდა ვუკეთო
** კომპონენტები
*** server
**** main app + rest api
- დღეში რამდენჯერმე შეამოწმებს ამანათების სტატუსს/ახალ ამანათს მომხმარებლისთვის
- გამოიძახებს სერვისებს ავტომატურად დასადეკლარირებლად
- მომხმარებელს შეატყობინებს სიახლეებს
- მიაწოდებს მონაცემთა ბაზის ინფორმაციას frontს
**** database
შეინახავს
- ინფორმაციას ამანათებზე
- სხვადასხვა საიტების api tokenებს, ბოლო შემოწმების თარიღს, etc
- ? მისამართებს
**** სერვისი - selenium
api reverse engineeringში ვერ ვერკვევი, ამიტომ ჯავასკრიპტით ან პითონით გამოვიყენებ სელენიუმს (მაგაზე მუშაობა დაწყებული მქონდა არეული სკრიპტით და თავიდან გავაკეთებ)
- ახლა ორიენტირებული ვიქნები usa2georgia და amanati.geზე
*** client
**** pwa Front End
ძალიან მარტივი interface მონაცემთა ბაზისთვის, reactში აწყობილი (ცოტა ხანს სწავლას დავუთმობ დროს). რადგანაც ყველა ენასა თუ ტექნოლოგიაში მცირე გამოცდილება მაქვს, ვფიქრობ კარგი იქნება ახლის ათვისების უნარის ჩვენება.
**** browser extension
- თუ დასაწყისში ebay და amazon apiსთან მარტივად ვერ დავმეგობრდი (ან დრო არ მქონდა), ღილაკი იქნება რომელიც გახსნილი ვებ გვერდიდან ინფორმაციას აიღებს
*** misc
**** სკრიპტი წარსული
(რადგან )
* გეგმა
** first sprint
